import { Source } from "./types";

export const SOURCE_REGISTRY: Source[] = [
  {
    name: "Global Voices",
    websiteUrl: "https://globalvoices.org",
    feedUrl: "https://globalvoices.org/feed/",
    licenseName: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    allowsCommercialUse: true,
    allowsDerivatives: true,
    attributionRequirement: "Credit Global Voices with a link back to the original article.",
    imageRestrictions: "Images may be separately licensed by third-party photographers — verify per-image before reuse.",
    republicationNotes: "See Global Voices Attribution Policy: https://globalvoices.org/about/global-voices-attribution-policy/",
    defaultCategory: "world",
    active: true,
  },
  {
    name: "Horizon Magazine",
    websiteUrl: "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine",
    feedUrl: "https://research-and-innovation.ec.europa.eu/node/2/rss_en?f%5B0%5D=topic_topic%3A150",
    licenseName: "EU standard reuse policy (attribution required)",
    licenseUrl: "https://commission.europa.eu/legal-notice_en",
    allowsCommercialUse: true,
    allowsDerivatives: true,
    attributionRequirement: "Credit Horizon Magazine / European Commission, link back to the original article.",
    imageRestrictions: "Images may be separately licensed — verify per-image before reuse.",
    republicationNotes: "Articles republished under the EU's standard attribution-based reuse policy for institutional content.",
    defaultCategory: "science",
    active: true,
  },
  {
    name: "The Dev Newsletter",
    websiteUrl: "https://devnewsletter.com",
    feedUrl: "https://devnewsletter.com/feed.xml",
    licenseName: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    allowsCommercialUse: true,
    allowsDerivatives: true,
    attributionRequirement: "Credit The Dev Newsletter, link back to the original article.",
    imageRestrictions: "Not specified — verify per-image before reuse.",
    republicationNotes: "Site explicitly welcomes bot/automated access per their Terms of Service (devnewsletter.com/terms/).",
    defaultCategory: "technology",
    active: true,
  },
  {
    name: "SciDev.Net",
    websiteUrl: "https://www.scidev.net",
    feedUrl: "https://www.scidev.net/global/global_rss.xml",
    licenseName: "Unverified — republication guidelines (not confirmed as CC BY-equivalent)",
    licenseUrl: "https://www.scidev.net/global/content/media.html",
    allowsCommercialUse: false,
    allowsDerivatives: false,
    attributionRequirement: "Credit required at start of excerpt, byline required where possible, limited to first 3 paragraphs per their stated guidelines — terms read more restrictive than a standard CC BY license.",
    imageRestrictions: "Not verified.",
    republicationNotes: "HELD, not active: their own reuse page describes a curated excerpt-republication process, not a clear open license. Revisit and verify directly with SciDev.Net before enabling.",
    defaultCategory: "science",
    active: false,
  },
  {
    name: "European Commission Press Corner",
    websiteUrl: "https://ec.europa.eu/commission/presscorner",
    feedUrl: "https://ec.europa.eu/commission/presscorner/api/rss",
    licenseName: "EU standard reuse policy (attribution required)",
    licenseUrl: "https://commission.europa.eu/legal-notice_en",
    allowsCommercialUse: true,
    allowsDerivatives: true,
    attributionRequirement: "Credit European Commission, link back to the original press release.",
    imageRestrictions: "Feed is text-only, no enclosure images observed — not applicable in practice.",
    republicationNotes: "General EU press feed (all policy areas), not sport-specific. No server-side category filter exists (tested directly — query params are ignored), so filtering happens client-side via categoryFilter. Sport items cluster around EU sport-policy calendar events (e.g. European Week of Sport), so most days will yield zero matches — kept active anyway since polling costs nothing.",
    defaultCategory: "sports",
    active: true,
    categoryFilter: (categories) => {
      const joined = categories.join(",");
      return joined.includes("SPORT") ? "sports" : null;
    },
  },
];